name: Automate LeetCode Submission

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install selenium

    - name: Run Selenium script
      run: python script.py
      env:
        LEETCODE_USERNAME: ${{ secrets.LC_USERNAME }}
        LEETCODE_PASSWORD: ${{ secrets.LC_PASSWORD }}
        # Add any other secrets or environment variables your script needs
