name: LeetCode Automation

on:
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Selenium WebDriver
      run: npm install selenium-webdriver

    - name: Run LeetCode Automation script
      env:
        LC_USERNAME: ${{ secrets.LC_USERNAME }}
        LC_PASSWORD: ${{ secrets.LC_PASSWORD }}
      run: node automation.js
